package servidorNotificaciones.sop_corba;


/**
* servidorNotificaciones/sop_corba/GestionNotificacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones.idl
* jueves 18 de junio de 2020 03:46:49 PM COT
*/

public interface GestionNotificacionesOperations 
{
  void notificarRegistro (servidorNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO objNotificacion);
} // interface GestionNotificacionesOperations
