package servidorNotificaciones.sop_corba;

/**
* servidorNotificaciones/sop_corba/GestionNotificacionesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones.idl
* jueves 18 de junio de 2020 03:46:49 PM COT
*/

public final class GestionNotificacionesHolder implements org.omg.CORBA.portable.Streamable
{
  public servidorNotificaciones.sop_corba.GestionNotificaciones value = null;

  public GestionNotificacionesHolder ()
  {
  }

  public GestionNotificacionesHolder (servidorNotificaciones.sop_corba.GestionNotificaciones initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servidorNotificaciones.sop_corba.GestionNotificacionesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servidorNotificaciones.sop_corba.GestionNotificacionesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servidorNotificaciones.sop_corba.GestionNotificacionesHelper.type ();
  }

}
