package servidorNotificaciones.sop_corba;

/**
* servidorNotificaciones/sop_corba/NotificacionIntHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones.idl
* miércoles 24 de junio de 2020 03:23:09 AM COT
*/

public final class NotificacionIntHolder implements org.omg.CORBA.portable.Streamable
{
  public servidorNotificaciones.sop_corba.NotificacionInt value = null;

  public NotificacionIntHolder ()
  {
  }

  public NotificacionIntHolder (servidorNotificaciones.sop_corba.NotificacionInt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servidorNotificaciones.sop_corba.NotificacionIntHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servidorNotificaciones.sop_corba.NotificacionIntHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servidorNotificaciones.sop_corba.NotificacionIntHelper.type ();
  }

}
