package servidorNotificaciones.sop_corba;


/**
* servidorNotificaciones/sop_corba/NotificacionInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones.idl
* domingo 21 de junio de 2020 04:10:42 PM COT
*/

public interface NotificacionInt extends NotificacionIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface NotificacionInt
