package servidorNotificaciones.sop_corba;


/**
* servidorNotificaciones/sop_corba/NotificacionIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones.idl
* domingo 21 de junio de 2020 04:10:42 PM COT
*/

public abstract class NotificacionIntPOA extends org.omg.PortableServer.Servant
 implements servidorNotificaciones.sop_corba.NotificacionIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("notificarRegistro", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // servidorNotificaciones/sop_corba/NotificacionInt/notificarRegistro
       {
         servidorNotificaciones.sop_corba.NotificacionIntPackage.ClsMensajeNotificacionDTO objMensajeNotificacion = servidorNotificaciones.sop_corba.NotificacionIntPackage.ClsMensajeNotificacionDTOHelper.read (in);
         this.notificarRegistro (objMensajeNotificacion);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:servidorNotificaciones/sop_corba/NotificacionInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public NotificacionInt _this() 
  {
    return NotificacionIntHelper.narrow(
    super._this_object());
  }

  public NotificacionInt _this(org.omg.CORBA.ORB orb) 
  {
    return NotificacionIntHelper.narrow(
    super._this_object(orb));
  }


} // class NotificacionIntPOA
