package servidorNotificaciones.sop_corba;


/**
* servidorNotificaciones/sop_corba/NotificacionIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones.idl
* miércoles 24 de junio de 2020 03:23:09 AM COT
*/

public interface NotificacionIntOperations 
{
  void notificarRegistro (servidorNotificaciones.sop_corba.NotificacionIntPackage.ClsMensajeNotificacionDTO objMensajeNotificacion);
} // interface NotificacionIntOperations
