package servidorNotificaciones.sop_corba;


/**
* servidorNotificaciones/sop_corba/NotificacionIntPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones.idl
* miércoles 24 de junio de 2020 03:23:09 AM COT
*/

public class NotificacionIntPOATie extends NotificacionIntPOA
{

  // Constructors

  public NotificacionIntPOATie ( servidorNotificaciones.sop_corba.NotificacionIntOperations delegate ) {
      this._impl = delegate;
  }
  public NotificacionIntPOATie ( servidorNotificaciones.sop_corba.NotificacionIntOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public servidorNotificaciones.sop_corba.NotificacionIntOperations _delegate() {
      return this._impl;
  }
  public void _delegate (servidorNotificaciones.sop_corba.NotificacionIntOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void notificarRegistro (servidorNotificaciones.sop_corba.NotificacionIntPackage.ClsMensajeNotificacionDTO objMensajeNotificacion)
  {
    _impl.notificarRegistro(objMensajeNotificacion);
  } // notificarRegistro

  private servidorNotificaciones.sop_corba.NotificacionIntOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class NotificacionIntPOATie
