package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/_GestionAsintomaticosIntStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from salertas.idl
* domingo 21 de junio de 2020 11:50:32 PM COT
*/

public class _GestionAsintomaticosIntStub extends org.omg.CORBA.portable.ObjectImpl implements servidorAlertas.sop_corba.GestionAsintomaticosInt
{

  public boolean registrarAsintomatico (servidorAlertas.sop_corba.ClsAsintomaticoDTO objAsintomaticoDTO)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarAsintomatico", true);
                servidorAlertas.sop_corba.ClsAsintomaticoDTOHelper.write ($out, objAsintomaticoDTO);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrarAsintomatico (objAsintomaticoDTO        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarAsintomatico

  public servidorAlertas.sop_corba.ClsAsintomaticoDTO consultarAsintomatico (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarAsintomatico", true);
                $out.write_long (id);
                $in = _invoke ($out);
                servidorAlertas.sop_corba.ClsAsintomaticoDTO $result = servidorAlertas.sop_corba.ClsAsintomaticoDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarAsintomatico (id        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarAsintomatico

  public boolean enviarIndicadores (int id, int frecuenciaCardiaca, int frecuenciaRespiratoria, float temperatura)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("enviarIndicadores", true);
                $out.write_long (id);
                $out.write_long (frecuenciaCardiaca);
                $out.write_long (frecuenciaRespiratoria);
                $out.write_float (temperatura);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return enviarIndicadores (id, frecuenciaCardiaca, frecuenciaRespiratoria, temperatura        );
            } finally {
                _releaseReply ($in);
            }
  } // enviarIndicadores

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:servidorAlertas/sop_corba/GestionAsintomaticosInt:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GestionAsintomaticosIntStub
