package servidorAlertas.sop_corba;

/**
* servidorAlertas/sop_corba/AsintomaticoCllbckIntHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from salertas.idl
* domingo 21 de junio de 2020 11:50:32 PM COT
*/

public final class AsintomaticoCllbckIntHolder implements org.omg.CORBA.portable.Streamable
{
  public servidorAlertas.sop_corba.AsintomaticoCllbckInt value = null;

  public AsintomaticoCllbckIntHolder ()
  {
  }

  public AsintomaticoCllbckIntHolder (servidorAlertas.sop_corba.AsintomaticoCllbckInt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servidorAlertas.sop_corba.AsintomaticoCllbckIntHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servidorAlertas.sop_corba.AsintomaticoCllbckIntHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servidorAlertas.sop_corba.AsintomaticoCllbckIntHelper.type ();
  }

}
