package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/AsintomaticoCllbckIntPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from salertas.idl
* domingo 21 de junio de 2020 11:50:32 PM COT
*/

public class AsintomaticoCllbckIntPOATie extends AsintomaticoCllbckIntPOA
{

  // Constructors

  public AsintomaticoCllbckIntPOATie ( servidorAlertas.sop_corba.AsintomaticoCllbckIntOperations delegate ) {
      this._impl = delegate;
  }
  public AsintomaticoCllbckIntPOATie ( servidorAlertas.sop_corba.AsintomaticoCllbckIntOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public servidorAlertas.sop_corba.AsintomaticoCllbckIntOperations _delegate() {
      return this._impl;
  }
  public void _delegate (servidorAlertas.sop_corba.AsintomaticoCllbckIntOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void notificarMensajeCllbck (String mensaje)
  {
    _impl.notificarMensajeCllbck(mensaje);
  } // notificarMensajeCllbck

  private servidorAlertas.sop_corba.AsintomaticoCllbckIntOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class AsintomaticoCllbckIntPOATie
