package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/AsintomaticoCllbckIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from salertas.idl
* domingo 21 de junio de 2020 11:50:32 PM COT
*/

public interface AsintomaticoCllbckIntOperations 
{
  void notificarMensajeCllbck (String mensaje);
} // interface AsintomaticoCllbckIntOperations
