package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/ClsAsintomaticoDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from salertas.idl
* domingo 21 de junio de 2020 11:50:32 PM COT
*/

public final class ClsAsintomaticoDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String nombres = null;
  public String apellidos = null;
  public String tipo_id = null;
  public int id = (int)0;
  public String direccion = null;
  public servidorAlertas.sop_corba.AsintomaticoCllbckInt objAsintomaticoCllbck = null;

  public ClsAsintomaticoDTO ()
  {
  } // ctor

  public ClsAsintomaticoDTO (String _nombres, String _apellidos, String _tipo_id, int _id, String _direccion, servidorAlertas.sop_corba.AsintomaticoCllbckInt _objAsintomaticoCllbck)
  {
    nombres = _nombres;
    apellidos = _apellidos;
    tipo_id = _tipo_id;
    id = _id;
    direccion = _direccion;
    objAsintomaticoCllbck = _objAsintomaticoCllbck;
  } // ctor

} // class ClsAsintomaticoDTO
