package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/GestionAsintomaticosIntPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from salertas.idl
* domingo 21 de junio de 2020 11:50:32 PM COT
*/

public class GestionAsintomaticosIntPOATie extends GestionAsintomaticosIntPOA
{

  // Constructors

  public GestionAsintomaticosIntPOATie ( servidorAlertas.sop_corba.GestionAsintomaticosIntOperations delegate ) {
      this._impl = delegate;
  }
  public GestionAsintomaticosIntPOATie ( servidorAlertas.sop_corba.GestionAsintomaticosIntOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public servidorAlertas.sop_corba.GestionAsintomaticosIntOperations _delegate() {
      return this._impl;
  }
  public void _delegate (servidorAlertas.sop_corba.GestionAsintomaticosIntOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean registrarAsintomatico (servidorAlertas.sop_corba.ClsAsintomaticoDTO objAsintomaticoDTO)
  {
    return _impl.registrarAsintomatico(objAsintomaticoDTO);
  } // registrarAsintomatico

  public servidorAlertas.sop_corba.ClsAsintomaticoDTO consultarAsintomatico (int id)
  {
    return _impl.consultarAsintomatico(id);
  } // consultarAsintomatico

  public boolean enviarIndicadores (int id, int frecuenciaCardiaca, int frecuenciaRespiratoria, float temperatura)
  {
    return _impl.enviarIndicadores(id, frecuenciaCardiaca, frecuenciaRespiratoria, temperatura);
  } // enviarIndicadores

  private servidorAlertas.sop_corba.GestionAsintomaticosIntOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class GestionAsintomaticosIntPOATie
