package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/GestionAsintomaticos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges-asintomaticos.idl
* jueves 18 de junio de 2020 03:00:38 PM COT
*/

public interface GestionAsintomaticos extends GestionAsintomaticosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionAsintomaticos
