package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/GestionAsintomaticosPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges-asintomaticos.idl
* jueves 18 de junio de 2020 03:00:38 PM COT
*/

public abstract class GestionAsintomaticosPOA extends org.omg.PortableServer.Servant
 implements servidorAlertas.sop_corba.GestionAsintomaticosOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registrarAsintomatico", new java.lang.Integer (0));
    _methods.put ("consultarAsintomatico", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/GestionAsintomaticos/registrarAsintomatico
       {
         servidorAlertas.sop_corba.GestionAsintomaticosPackage.asintomaticoDTO asin_reg = servidorAlertas.sop_corba.GestionAsintomaticosPackage.asintomaticoDTOHelper.read (in);
         org.omg.CORBA.BooleanHolder res = new org.omg.CORBA.BooleanHolder ();
         this.registrarAsintomatico (asin_reg, res);
         out = $rh.createReply();
         out.write_boolean (res.value);
         break;
       }

       case 1:  // sop_corba/GestionAsintomaticos/consultarAsintomatico
       {
         int id = in.read_long ();
         servidorAlertas.sop_corba.GestionAsintomaticosPackage.asintomaticoDTOHolder asin_bus = new servidorAlertas.sop_corba.GestionAsintomaticosPackage.asintomaticoDTOHolder ();
         boolean $result = false;
         $result = this.consultarAsintomatico (id, asin_bus);
         out = $rh.createReply();
         out.write_boolean ($result);
         servidorAlertas.sop_corba.GestionAsintomaticosPackage.asintomaticoDTOHelper.write (out, asin_bus.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionAsintomaticos:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionAsintomaticos _this() 
  {
    return GestionAsintomaticosHelper.narrow(
    super._this_object());
  }

  public GestionAsintomaticos _this(org.omg.CORBA.ORB orb) 
  {
    return GestionAsintomaticosHelper.narrow(
    super._this_object(orb));
  }


} // class GestionAsintomaticosPOA
