package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/GestionAsintomaticosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges-asintomaticos.idl
* jueves 18 de junio de 2020 03:00:38 PM COT
*/

public interface GestionAsintomaticosOperations 
{
  void registrarAsintomatico (servidorAlertas.sop_corba.GestionAsintomaticosPackage.asintomaticoDTO asin_reg, org.omg.CORBA.BooleanHolder res);
  boolean consultarAsintomatico (int id, servidorAlertas.sop_corba.GestionAsintomaticosPackage.asintomaticoDTOHolder asin_bus);
} // interface GestionAsintomaticosOperations
