package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/GestionAsintomaticosPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges-asintomaticos.idl
* jueves 18 de junio de 2020 03:00:37 PM COT
*/

public class GestionAsintomaticosPOATie extends GestionAsintomaticosPOA
{

  // Constructors

  public GestionAsintomaticosPOATie ( servidorAlertas.sop_corba.GestionAsintomaticosOperations delegate ) {
      this._impl = delegate;
  }
  public GestionAsintomaticosPOATie ( servidorAlertas.sop_corba.GestionAsintomaticosOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public servidorAlertas.sop_corba.GestionAsintomaticosOperations _delegate() {
      return this._impl;
  }
  public void _delegate (servidorAlertas.sop_corba.GestionAsintomaticosOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void registrarAsintomatico (servidorAlertas.sop_corba.GestionAsintomaticosPackage.asintomaticoDTO asin_reg, org.omg.CORBA.BooleanHolder res)
  {
    _impl.registrarAsintomatico(asin_reg, res);
  } // registrarAsintomatico

  public boolean consultarAsintomatico (int id, servidorAlertas.sop_corba.GestionAsintomaticosPackage.asintomaticoDTOHolder asin_bus)
  {
    return _impl.consultarAsintomatico(id, asin_bus);
  } // consultarAsintomatico

  private servidorAlertas.sop_corba.GestionAsintomaticosOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class GestionAsintomaticosPOATie
