package servidorNotificaciones.sop_corba.GestionNotificacionesPackage;

/**
* servidorNotificaciones/sop_corba/GestionNotificacionesPackage/ClsMensajeNotificacionDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones.idl
* jueves 18 de junio de 2020 03:46:49 PM COT
*/

public final class ClsMensajeNotificacionDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public servidorNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO value = null;

  public ClsMensajeNotificacionDTOHolder ()
  {
  }

  public ClsMensajeNotificacionDTOHolder (servidorNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servidorNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servidorNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servidorNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTOHelper.type ();
  }

}
