package servidorNotificaciones.sop_corba.GestionNotificacionesPackage;


/**
* servidorNotificaciones/sop_corba/GestionNotificacionesPackage/ClsMensajeNotificacionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones.idl
* jueves 18 de junio de 2020 03:46:49 PM COT
*/

public final class ClsMensajeNotificacionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String mensaje = null;

  public ClsMensajeNotificacionDTO ()
  {
  } // ctor

  public ClsMensajeNotificacionDTO (String _mensaje)
  {
    mensaje = _mensaje;
  } // ctor

} // class ClsMensajeNotificacionDTO
