package servidorNotificaciones.sop_corba.NotificacionIntPackage;


/**
* servidorNotificaciones/sop_corba/NotificacionIntPackage/ClsMensajeNotificacionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones.idl
* miércoles 24 de junio de 2020 03:23:09 AM COT
*/

public final class ClsMensajeNotificacionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String nombres = null;
  public String apellidos = null;
  public String tipo_id = null;
  public int id = (int)0;
  public String direccion = null;
  public int frecuenciaCardiaca = (int)0;
  public int frecuenciaRespiratoria = (int)0;
  public float temperatura = (float)0;
  public String fechaAlerta = null;
  public String horaAlerta = null;
  public String mensaje = null;

  public ClsMensajeNotificacionDTO ()
  {
  } // ctor

  public ClsMensajeNotificacionDTO (String _nombres, String _apellidos, String _tipo_id, int _id, String _direccion, int _frecuenciaCardiaca, int _frecuenciaRespiratoria, float _temperatura, String _fechaAlerta, String _horaAlerta, String _mensaje)
  {
    nombres = _nombres;
    apellidos = _apellidos;
    tipo_id = _tipo_id;
    id = _id;
    direccion = _direccion;
    frecuenciaCardiaca = _frecuenciaCardiaca;
    frecuenciaRespiratoria = _frecuenciaRespiratoria;
    temperatura = _temperatura;
    fechaAlerta = _fechaAlerta;
    horaAlerta = _horaAlerta;
    mensaje = _mensaje;
  } // ctor

} // class ClsMensajeNotificacionDTO
