package servidorNotificaciones.sop_corba.NotificacionIntPackage;

import servidorAlertas.sop_corba.ClsAsintomaticoDTO;


/**
* servidorNotificaciones/sop_corba/NotificacionIntPackage/ClsMensajeNotificacionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones.idl
* domingo 21 de junio de 2020 04:10:42 PM COT
*/

public final class ClsMensajeNotificacionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public ClsAsintomaticoDTO pacienteAsintomatico = null;
  public int frecuenciaCardiaca = (int)0;
  public int frecuenciaRespiratoria = (int)0;
  public float temperatura = (float)0;
  public String fechaAlerta = null;
  public String horaAlerta = null;
  public String mensaje = null;

  public ClsMensajeNotificacionDTO ()
  {
  } // ctor

  public ClsMensajeNotificacionDTO (ClsAsintomaticoDTO _pacienteAsintomatico, int _frecuenciaCardiaca, int _frecuenciaRespiratoria, float _temperatura, String _fechaAlerta, String _horaAlerta, String _mensaje)
  {
    pacienteAsintomatico = _pacienteAsintomatico;
    frecuenciaCardiaca = _frecuenciaCardiaca;
    frecuenciaRespiratoria = _frecuenciaRespiratoria;
    temperatura = _temperatura;
    fechaAlerta = _fechaAlerta;
    horaAlerta = _horaAlerta;
    mensaje = _mensaje;
  } // ctor

} // class ClsMensajeNotificacionDTO
