package servidorAlertas.sop_corba.GestionAsintomaticosPackage;

/**
* servidorAlertas/sop_corba/GestionAsintomaticosPackage/asintomaticoDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges-asintomaticos.idl
* jueves 18 de junio de 2020 03:00:38 PM COT
*/

public final class asintomaticoDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public servidorAlertas.sop_corba.GestionAsintomaticosPackage.asintomaticoDTO value = null;

  public asintomaticoDTOHolder ()
  {
  }

  public asintomaticoDTOHolder (servidorAlertas.sop_corba.GestionAsintomaticosPackage.asintomaticoDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servidorAlertas.sop_corba.GestionAsintomaticosPackage.asintomaticoDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servidorAlertas.sop_corba.GestionAsintomaticosPackage.asintomaticoDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servidorAlertas.sop_corba.GestionAsintomaticosPackage.asintomaticoDTOHelper.type ();
  }

}
