package servidorAlertas.sop_corba.GestionAsintomaticosPackage;


/**
* servidorAlertas/sop_corba/GestionAsintomaticosPackage/asintomaticoDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges-asintomaticos.idl
* jueves 18 de junio de 2020 03:00:38 PM COT
*/

public final class asintomaticoDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String nombres = null;
  public String apellidos = null;
  public String tipo_id = null;
  public int id = (int)0;
  public String direccion = null;

  public asintomaticoDTO ()
  {
  } // ctor

  public asintomaticoDTO (String _nombres, String _apellidos, String _tipo_id, int _id, String _direccion)
  {
    nombres = _nombres;
    apellidos = _apellidos;
    tipo_id = _tipo_id;
    id = _id;
    direccion = _direccion;
  } // ctor

} // class asintomaticoDTO
