module sop_corba{
interface GestionAsintomaticos{
struct asintomaticoDTO{
string nombres;
string apellidos;
string tipo_id;
long id;
string direccion;
};

void registrarAsintomatico(in asintomaticoDTO asin_reg,out boolean res);
boolean consultarAsintomatico(in long id,out asintomaticoDTO asin_bus);
};
};
