module servidorNotificaciones{
	module sop_corba{
	    interface NotificacionInt{
		struct ClsAsintomaticoDTO{
			     string nombres;
		  	     string apellidos;
			     string tipo_id;
			     long id;
			     string direccion;
		};

		struct ClsMensajeNotificacionDTO{
			  ClsAsintomaticoDTO pacienteAsintomatico;
		       	  long frecuenciaCardiaca;
			  long frecuenciaRespiratoria;
		      	  float temperatura;
			  string fechaAlerta;
			  string horaAlerta;
			  string mensaje;
		};

	
		void notificarRegistro(in ClsMensajeNotificacionDTO objMensajeNotificacion);
	};
   };

};
