module servidorNotificaciones{
	module sop_corba{
	    interface NotificacionInt{
		struct ClsMensajeNotificacionDTO{
			 string nombres;
		  	 string apellidos;
			 string tipo_id;
			 long id;
			 string direccion;	
		       	 long frecuenciaCardiaca;
			 long frecuenciaRespiratoria;
		      	 float temperatura;
			 string fechaAlerta;
			 string horaAlerta;
			 string mensaje;
		};

	
		void notificarRegistro(in ClsMensajeNotificacionDTO objMensajeNotificacion);
	};
   };

};
